name: Build
on: [ push, pull_request ]

jobs:
  build:
    name: Project build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U -r requirements.txt
          pip freeze > requirements.lock
          pip install -U -r requirements-dev.txt
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --exit-zero --tee --output-file=flake8-report
      - name: Test with pytest and coverage
        run: |
          coverage run -m pytest --junitxml=pytest-report.xml tests
          coverage xml -o coverage-pytest.xml
